#
# COPYRIGHT Ericsson 2023
#
# The copyright to the computer program(s) herein is the property of
# Ericsson Inc. The programs may be used and/or copied only with written
# permission from Ericsson Inc. or in accordance with the terms and
# conditions stipulated in the agreement/contract under which the
# program(s) have been supplied.
#

documents:
  # document name
  - name: user_guide
    # file names of files to be packaged in the document
    files:
      - ../doc/User_Guide/user_guide.md
      - ../doc/User_Guide/AIS_architecture_overview.png
      - ../doc/User_Guide/AIS_deployment_overview.png
#  - name: developers_guide
#    files:
#      - ../doc/app-dev-guide/application-developers-guide.md
#      - ../doc/app-dev-guide/pmsc-kpi-model.png

