{{- if  (eq (include "eric-oss-assurance-indexer.global-security-tls-enabled" .) "true") }}


#
# COPYRIGHT Ericsson 2023
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

apiVersion: siptls.sec.ericsson.com/v1
kind: InternalCertificate
metadata:
  name: {{ include "eric-oss-assurance-indexer.name" . }}-log-transformer-client-cert
  labels:
  {{- include "eric-oss-assurance-indexer.labels" . | nindent 4 }}
  annotations:
  {{- include "eric-oss-assurance-indexer.annotations" . | nindent 4 }}
spec:
  kubernetes:
    generatedSecretName: {{ include "eric-oss-assurance-indexer.name" . }}-log-transformer-client-cert
    certificateName: cert.crt
    privateKeyName: key.pem
  certificate:
    subject:
      cn: {{ include "eric-oss-assurance-indexer.name" . }}
    issuer:
      reference: eric-log-transformer-input-ca-cert
    extendedKeyUsage:
      tlsClientAuth: true
      tlsServerAuth: false
{{ end }}
